### ISSUE TITLE
HOME install and yajl availability

### ISSUE THREAD

**Issue by sagarchalise** [zhgzhg/Geany-JSON-Prettifier#4]
Currently, the `Makefile` tends to prepare bundled `yajl` and install into system which requires system access.

Maybe by default if not used by `sudo` or `root`:

- Install in `$HOME/.config/geany/plugins`
- Prepare bundled `yajl` only when system `yajl` is not available.

**Comment by zhgzhg** [comment]
Hi @sagarchalise , I've provided localinstall and localuninstall options in the Makefile, that do not require root permissions. Compilation of the bundled yajl is always required however, because the plugin links statically to it. No installation of the bundled yajl is done. This allows the plugin to function even in the case of removing the system's yajl.
