### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by own3mall** [zhgzhg/Geany-JSON-Prettifier#6]
Does this plugin support Geany in Windows?  Is there a precompiled dll somewhere for it?  I would love to use this plugin in Windows for Geany if possible!  

Please let me know.

**Comment by zhgzhg** [comment]
Hello, unfortunately not. This might change, but will be in the distant future though.

**Comment by own3mall** [comment]
@zhgzhg Thanks for the information.  :+1:

**Comment by zhgzhg** [comment]
@own3mall, it turns out that building a DLL for this particular plugin is quite straightforward.

I've attached it in the [release for v1.6.0](https://github.com/zhgzhg/Geany-JSON-Prettifier/releases/tag/v1.6.0). Installation can be done by placing jsonprettfier.dll inside "<Geany's Install Directory>\lib\geany" and restarting the editor. Then Geany's plugin manager should be able to detect it.

**Comment by own3mall** [comment]
@zhgzhg Working fine for me in Windows.  Thank you so much for this!

**Comment by fyah** [comment]
Hello,

would it be possible to get a x64 build ?
geany's for windows is not built any more in 32bits...

thanks a lot!

**Comment by zhgzhg** [comment]
Thanks for bringing this to my attention. I'll try to create a x64 build...

**Comment by zhgzhg** [comment]
@fyah , I've attached the 64bit version (x86_64) in [the release for v1.6.0](https://github.com/zhgzhg/Geany-JSON-Prettifier/releases/tag/v1.6.0). The installation is the same - by placing jsonprettfier_x86_64.dll inside "<Geany's Install Directory>\lib\geany" and restarting the editor

**Comment by fyah** [comment]
@zhgzhg  I confirm it works like a charm, thanks a lot!
(had to report false positive to antivirus before beeing able to load ....)

**Comment by zhgzhg** [comment]
Excellent, closing the ticket!
