### ISSUE TITLE
Plugin not installing on Geany 1.27, ubuntu 16.04

### ISSUE THREAD

**Issue by beeryukov** [zhgzhg/Geany-JSON-Prettifier#8]
Hello! Could anyone help me to install (or activate?) this plugin.

I successfully built it, ran make localinstall. jsonprettifier.so appeared in ~/.config/geany/plugins. But nothing appeared inside the Geany app. Then I manually added the path to the glugin to active_plugins setting in geany.conf. But still cannot see it in the app.
When running geany from command line no errors are displayed.
All other plugins work normally, so plugins support itself is enabled. 
What else do I miss?

**Comment by zhgzhg** [comment]
Hi @beeryukov ,
Not being able see the plugin inside Geany's plugin manager menu can be caused by the old version of Geany - 1.27 is several years old. In this case you can try 2 things:

- Install an older version of the plugin, perhaps between v1.3 - v.1.4.2

- Attempt to patch the Geany version constraint set in the plugin by changing the following value in:
https://github.com/zhgzhg/Geany-JSON-Prettifier/blob/e9f8441ace2d213dea5541637ec453f242eaa104/geany_json_prettifier.c#L50
to something smaller like `224` instead of `235`.

**Comment by beeryukov** [comment]
Thank you! `PLUGIN_VERSION_CHECK(224)` worked.
